# Generated by Django 2.1.5 on 2019-01-21 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('player', 'Player'), ('developer', 'Developer')], max_length=20)),
                ('games', models.ManyToManyField(to='games.Game')),
            ],
        ),
    ]
