# Generated by Django 2.1.5 on 2019-02-13 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20190208_1627'),
        ('orders', '0002_auto_20190208_1723'),
    ]

    operations = [
    ]
