# Generated by Django 2.1.5 on 2019-02-13 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20190208_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ref',
            field=models.CharField(default=' ', max_length=255),
            preserve_default=False,
        ),
    ]
