# Generated by Django 2.1.5 on 2019-02-14 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_merge_20190213_1821'),
        ('orders', '0003_order_ref'),
    ]

    operations = [
    ]
