# Generated by Django 2.1.5 on 2019-02-14 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_merge_20190213_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ref',
            field=models.CharField(default='ref', max_length=255),
            preserve_default=False,
        ),
    ]
