# Generated by Django 2.1.5 on 2019-02-18 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_merge_20190214_1724'),
        ('orders', '0004_order_ref'),
    ]

    operations = [
    ]
