# Generated by Django 2.1.5 on 2019-02-01 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='orders.Order'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected'), ('error', 'Error')], default=('waiting', 'Waiting'), max_length=10),
        ),
    ]
